name: nuget-build-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Display dotnet version
        run: dotnet --version
      - name: Run cake
        shell : bash
        env:          
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd ./src/BasicInMemEventBus
          dotnet new tool-manifest
          dotnet tool install Cake.Tool --version 3.0.0
          dotnet tool restore
          dotnet cake --force

