name: nuget-build-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']    
    steps:
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Display dotnet version
      run: dotnet --version        
    - name: Check out Code
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Run cake
      shell : bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |         
        dotnet new tool-manifest
        dotnet tool install Cake.Tool
        dotnet tool restore
        dotnet dotnet-cake ./src/BasicInMemEventBus/build.cake