name: nuget-build-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Restore dependencies
        run: dotnet restore ./src/BasicInMemEventBus.sln
      - name: Build
        run: dotnet build --no-restore --configuration release ./src/BasicInMemEventBus.sln /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release ./src/BasicInMemEventBus.Tests/BasicInMemEventBus.Tests.csproj /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }}
      - name: Package nuget
        run: dotnet pack ./src/BasicInMemEventBus/BasicInMemEventBus.csproj --configuration Release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./package/*.nupkg  --source https://nuget.pkg.github.com/DBCoderAtLarge/index.json   --api-key ${{ github.token }}
